log:
  name: delay-queue # Logger的名字
  development: true # 是否是开发模式。如果是开发模式，会对DPanicLevel进行堆栈跟踪。
  level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
  format: json # 支持的日志输出格式，目前支持console和json两种。console其实就是text格式。
  enable-color: true # 是否开启颜色输出，true:是，false:否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
  disable-stacktrace: false # 是否再panic及以上级别禁止打印堆栈信息
  output-paths:  # 支持输出到多个输出，逗号分开。支持输出到标准输出（stdout）和文件。
  error-output-paths: # zap内部(非业务)错误日志输出路径，多个输出，逗号分开
# Redis 配置
redis:
  host:  # redis 地址，默认 127.0.0.1:6379
  port: 6379 # redis 端口，默认 6379
  password:  # redis 密码
  addrs:
  master-name: # redis 集群 master 名称
  username: # redis 登录用户名
  database: # redis 数据库
  optimisation-max-idle: 20 # redis 连接池中的最大空闲连接数
  optimisation-max-active: 10 # 最大活跃连接数
  timeout: 10 # 连接 redis 时的超时时间
  enable-cluster: false # 是否开启集群模式
  use-ssl: false # 是否启用 TLS
  ssl-insecure-skip-verify: false # 当连接 redis 时允许使用自签名证书
# GRPC 服务配置
grpc:
  bind-address: 127.0.0.1 # grpc 安全模式的 IP 地址，默认 0.0.0.0
  bind-port: 9596 # grpc 安全模式的端口号，默认 8081