// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/job.proto

package job

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	DelaySeconds         uint64   `protobuf:"varint,2,opt,name=delaySeconds,proto3" json:"delaySeconds,omitempty"`
	TtrSeconds           uint64   `protobuf:"varint,3,opt,name=ttrSeconds,proto3" json:"ttrSeconds,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	IsLoop               bool     `protobuf:"varint,5,opt,name=isLoop,proto3" json:"isLoop,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,6,opt,name=notifyUrl,proto3" json:"notifyUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5e2baf7640c8fed, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *AddRequest) GetDelaySeconds() uint64 {
	if m != nil {
		return m.DelaySeconds
	}
	return 0
}

func (m *AddRequest) GetTtrSeconds() uint64 {
	if m != nil {
		return m.TtrSeconds
	}
	return 0
}

func (m *AddRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *AddRequest) GetIsLoop() bool {
	if m != nil {
		return m.IsLoop
	}
	return false
}

func (m *AddRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

type AddReply struct {
	JobId                string   `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReply) Reset()         { *m = AddReply{} }
func (m *AddReply) String() string { return proto.CompactTextString(m) }
func (*AddReply) ProtoMessage()    {}
func (*AddReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5e2baf7640c8fed, []int{1}
}

func (m *AddReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReply.Unmarshal(m, b)
}
func (m *AddReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReply.Marshal(b, m, deterministic)
}
func (m *AddReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReply.Merge(m, src)
}
func (m *AddReply) XXX_Size() int {
	return xxx_messageInfo_AddReply.Size(m)
}
func (m *AddReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddReply proto.InternalMessageInfo

func (m *AddReply) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type DelRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelRequest) Reset()         { *m = DelRequest{} }
func (m *DelRequest) String() string { return proto.CompactTextString(m) }
func (*DelRequest) ProtoMessage()    {}
func (*DelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5e2baf7640c8fed, []int{2}
}

func (m *DelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRequest.Unmarshal(m, b)
}
func (m *DelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRequest.Marshal(b, m, deterministic)
}
func (m *DelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRequest.Merge(m, src)
}
func (m *DelRequest) XXX_Size() int {
	return xxx_messageInfo_DelRequest.Size(m)
}
func (m *DelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelRequest proto.InternalMessageInfo

func (m *DelRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type DelReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelReply) Reset()         { *m = DelReply{} }
func (m *DelReply) String() string { return proto.CompactTextString(m) }
func (*DelReply) ProtoMessage()    {}
func (*DelReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5e2baf7640c8fed, []int{3}
}

func (m *DelReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelReply.Unmarshal(m, b)
}
func (m *DelReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelReply.Marshal(b, m, deterministic)
}
func (m *DelReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelReply.Merge(m, src)
}
func (m *DelReply) XXX_Size() int {
	return xxx_messageInfo_DelReply.Size(m)
}
func (m *DelReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DelReply.DiscardUnknown(m)
}

var xxx_messageInfo_DelReply proto.InternalMessageInfo

type UpdateRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	DelaySeconds         uint64   `protobuf:"varint,2,opt,name=delaySeconds,proto3" json:"delaySeconds,omitempty"`
	TtrSeconds           uint64   `protobuf:"varint,3,opt,name=ttrSeconds,proto3" json:"ttrSeconds,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	IsLoop               bool     `protobuf:"varint,5,opt,name=isLoop,proto3" json:"isLoop,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,6,opt,name=notifyUrl,proto3" json:"notifyUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5e2baf7640c8fed, []int{4}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *UpdateRequest) GetDelaySeconds() uint64 {
	if m != nil {
		return m.DelaySeconds
	}
	return 0
}

func (m *UpdateRequest) GetTtrSeconds() uint64 {
	if m != nil {
		return m.TtrSeconds
	}
	return 0
}

func (m *UpdateRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *UpdateRequest) GetIsLoop() bool {
	if m != nil {
		return m.IsLoop
	}
	return false
}

func (m *UpdateRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

type UpdateReply struct {
	JobId                string   `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReply) Reset()         { *m = UpdateReply{} }
func (m *UpdateReply) String() string { return proto.CompactTextString(m) }
func (*UpdateReply) ProtoMessage()    {}
func (*UpdateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5e2baf7640c8fed, []int{5}
}

func (m *UpdateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReply.Unmarshal(m, b)
}
func (m *UpdateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReply.Marshal(b, m, deterministic)
}
func (m *UpdateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReply.Merge(m, src)
}
func (m *UpdateReply) XXX_Size() int {
	return xxx_messageInfo_UpdateReply.Size(m)
}
func (m *UpdateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReply proto.InternalMessageInfo

func (m *UpdateReply) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "job.AddRequest")
	proto.RegisterType((*AddReply)(nil), "job.AddReply")
	proto.RegisterType((*DelRequest)(nil), "job.DelRequest")
	proto.RegisterType((*DelReply)(nil), "job.DelReply")
	proto.RegisterType((*UpdateRequest)(nil), "job.UpdateRequest")
	proto.RegisterType((*UpdateReply)(nil), "job.UpdateReply")
}

func init() { proto.RegisterFile("proto/job.proto", fileDescriptor_c5e2baf7640c8fed) }

var fileDescriptor_c5e2baf7640c8fed = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x52, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x25, 0xb6, 0x2b, 0xdd, 0xd5, 0x31, 0xb9, 0x88, 0x94, 0x21, 0x52, 0x22, 0x83, 0x3e, 0x55,
	0xd0, 0x2f, 0x18, 0xec, 0xc5, 0xe1, 0x53, 0x65, 0x1f, 0xb0, 0x98, 0x08, 0x2b, 0x61, 0x37, 0xb6,
	0xf1, 0x21, 0xcf, 0xfe, 0x90, 0xe0, 0x0f, 0x4a, 0xb3, 0x96, 0xb6, 0xa0, 0x3e, 0xef, 0xed, 0x9e,
	0x93, 0x73, 0x6f, 0x4e, 0xce, 0x0d, 0xcc, 0x4d, 0x45, 0x96, 0xee, 0x4b, 0x12, 0xb9, 0xaf, 0x30,
	0x28, 0x49, 0xf0, 0x2f, 0x06, 0xb0, 0x92, 0xb2, 0x50, 0xef, 0x1f, 0xaa, 0xb6, 0x78, 0x05, 0x93,
	0x92, 0xc4, 0x93, 0x4c, 0x58, 0xca, 0xb2, 0x69, 0x71, 0x04, 0xc8, 0xe1, 0x42, 0x2a, 0xbd, 0x73,
	0x2f, 0xea, 0x95, 0x0e, 0xb2, 0x4e, 0xce, 0x52, 0x96, 0x85, 0xc5, 0x88, 0xc3, 0x5b, 0x00, 0x6b,
	0xab, 0x4e, 0x11, 0x78, 0xc5, 0x80, 0x41, 0x84, 0x50, 0x90, 0x74, 0x49, 0xe8, 0x07, 0xfb, 0x1a,
	0xaf, 0x21, 0xda, 0xd7, 0xcf, 0x44, 0x26, 0x99, 0xa4, 0x2c, 0x8b, 0x8b, 0x16, 0xe1, 0x0d, 0x4c,
	0x0f, 0x64, 0xf7, 0x6f, 0x6e, 0x5b, 0xe9, 0x24, 0xf2, 0x0d, 0x3d, 0xc1, 0x53, 0x88, 0xbd, 0x63,
	0xa3, 0x5d, 0xe3, 0x77, 0x33, 0xf4, 0xeb, 0x01, 0xe7, 0x00, 0x6b, 0xa5, 0x07, 0x6f, 0xfa, 0x45,
	0x03, 0x10, 0x7b, 0x8d, 0xd1, 0x8e, 0x7f, 0x33, 0x98, 0x6d, 0x8d, 0xdc, 0x59, 0xf5, 0x6f, 0xcf,
	0x89, 0xe5, 0x70, 0x07, 0xe7, 0x9d, 0xe9, 0x3f, 0xa3, 0x78, 0xf8, 0x64, 0x10, 0x6c, 0x48, 0xe0,
	0x12, 0x82, 0x95, 0x94, 0x38, 0xcf, 0x9b, 0xfd, 0xf7, 0x0b, 0x5f, 0xcc, 0x7a, 0xa2, 0x19, 0xb2,
	0x84, 0x60, 0xad, 0x74, 0x2b, 0xeb, 0x33, 0x6c, 0x65, 0x5d, 0x60, 0x98, 0x43, 0x74, 0xbc, 0x1a,
	0xd1, 0x1f, 0x8c, 0xc2, 0x5b, 0x5c, 0x8e, 0x38, 0xa3, 0x9d, 0x88, 0xfc, 0x8f, 0x7b, 0xfc, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x1c, 0x3d, 0x1c, 0x29, 0x84, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error)
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelReply, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateReply, error)
}

type jobClient struct {
	cc *grpc.ClientConn
}

func NewJobClient(cc *grpc.ClientConn) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := c.cc.Invoke(ctx, "/job.Job/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelReply, error) {
	out := new(DelReply)
	err := c.cc.Invoke(ctx, "/job.Job/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateReply, error) {
	out := new(UpdateReply)
	err := c.cc.Invoke(ctx, "/job.Job/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServer is the server API for Job service.
type JobServer interface {
	Add(context.Context, *AddRequest) (*AddReply, error)
	Del(context.Context, *DelRequest) (*DelReply, error)
	Update(context.Context, *UpdateRequest) (*UpdateReply, error)
}

// UnimplementedJobServer can be embedded to have forward compatible implementations.
type UnimplementedJobServer struct {
}

func (*UnimplementedJobServer) Add(ctx context.Context, req *AddRequest) (*AddReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedJobServer) Del(ctx context.Context, req *DelRequest) (*DelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (*UnimplementedJobServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterJobServer(s *grpc.Server, srv JobServer) {
	s.RegisterService(&_Job_serviceDesc, srv)
}

func _Job_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.Job/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.Job/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.Job/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Job_serviceDesc = grpc.ServiceDesc{
	ServiceName: "job.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Job_Add_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Job_Del_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Job_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/job.proto",
}
